"""add clicks to urls

Revision ID: a994de633bd0
Revises: 56fcf77fa8da
Create Date: 2026-08-12 08:59:12.632539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994de633bd0'
down_revision: Union[str, Sequence[str], None] = '56fcf77fa8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls',
                   sa.Column('clicks', sa.Integer(), nullable=False, server_default= '0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###
